### ISSUE TITLE
FicsIt-OS doesn't boot.

### ISSUE THREAD

**Issue by DeXtRoDev** [Panakotta00/FicsIt-OS#1]
I installed the OS onto a fresh computer and tried to boot it. It won't start because of a read operation that fails. You can see the error stacktrace in the screenshot. I might have to do with the `filesystem.open("/etc/systemd.json")` part that is handed over to the `buffer.create` function in the 70_systemd.lua file (line 98).

[https://i.imgur.com/tC60w8s.png](url)

Would be great if this error gets fixed. Without such a basic OS it is quite annoying to program more complex apps in this mod.
As an idea: Maybe there's a way to implement a craftable ROM for the mod that already comes with an OS installed.

If you have any questions concerning the error, please feel free to ask.
Thanks, DeXtRo.

**Comment by Panakotta00** [comment]
I'm aware of the issue... I was just too lazy to fix it yet...
as quick fix, simple create the file /etc/systemd.json and insert `{}` as text.

Adding the OS as craftable ROM is certainly the idea to happen at some point, but the OS is no were near completionl.

For complex program development most "expert" FIN users use external IDEs like IntelliJ. You can use Drives etc to have a mirror of the ingame-filesystem on your real host-system with which it makes it very easy to write complex programs.
On the discord server we even have a Lua-Doc file to allow for auto-completion while coding in such IDE.
